### ISSUE TITLE
1.1.7 As a user, I want a sound card so that I can make the robot play back previously recorded sounds.

### ISSUE THREAD

**Issue by em135** [Xitric/AR-Programming#24]
### Tasks
- [ ] 1.1.7.1 Create a sound service for recording sounds with the microphone.
- [ ] 1.1.7.2 Create a sound service for storing recorded sounds in the app.
- [ ] 1.1.7.3 Create a sound service for playing back recorded sounds.

### Acceptance criteria
- Provide a button for recording and saving audio.
- Provide an option to the user for selecting the sound to be played by a sound card.
- When a sound card i reached, the sound is played back exactly once.
- Display an error message to the user when attempting to use a sound card without choosing a sound to be played.
