### ISSUE TITLE
1.1.10 As a user, I want a function card so that I can include previously constructed programs in new programs.

### ISSUE THREAD

**Issue by em135** [Xitric/AR-Programming#27]
### Tasks
- [x] 1.1.10.1 Add visual feedback in the UI for telling the user about the functions they have available.
- [x] 1.1.10.2 Allow for the user to store a program sequence rather than installing it directly to the robot.
- [x] 1.1.10.3 Allow for the user to assign previous programs to one or more active functions.

### Acceptance criteria
- Display the user's current main program and all functions in the game view.
- When a function card is reached, the entire function sequence is executed exactly once.
- Provide an option to discard previously saved functions.
- Display an error message to the user when attempting to use an undefined function.
- The user is able to understand, construct, and call a function after an initial introduction session by the teacher.
