### ISSUE TITLE
2.2.1 As a user, I want to be able to have a  simple guide in the app that can help me in the app, so I do not get stuck.

### ISSUE THREAD

**Issue by em135** [Xitric/AR-Programming#29]
### Tasks
- [ ] 2.2.1.1 Create a view for the guide.
- [ ] 2.2.1.2 Create description for cards with images, animation, sound.
- [ ] 2.2.1.3 Create description for gameplay with images, animation, sound.

### Acceptance criteria
- The guide can be viewed in the form of a video with voice-over.
