### ISSUE TITLE
2.2.2 As a user, I want to have a detailed manual that can explain in detail everything that is in the app, so I know how to use it and can teach others.

### ISSUE THREAD

**Issue by em135** [Xitric/AR-Programming#30]
### Tasks
- [ ] 2.2.2.1 Create a pdf for the manual.
- [ ] 2.2.2.2 Create a description for the cards.
- [ ] 2.2.2.3 Create a description for the gameplay and how to play.
- [ ] 2.2.2.4 Create a description for UI of the app and what each view is used for.

### Acceptance criteria
- The document describes every card avilable in the app.
- The document describes every view in the app.
- The document describes every type of level in the app.
