### ISSUE TITLE
2.3.1 As a user, I want to be able to customize the robot so that I can personalize it depending on my age, gender, and preferences.

### ISSUE THREAD

**Issue by em135** [Xitric/AR-Programming#32]
### Tasks
- [x] 2.3.1.1 Create robot models with various colors.
- [x] 2.3.1.2 Create a view for changing the appearance of the robot.
- [x] 2.3.1.3 Create a column in Core Data for storing the user’s choice.

### Acceptance criteria
- Display the total number of skins that the user can select between.
- Provide an option to view the skin in both a scene and AR view.
- Change the skin of the robot when sliding between the available selections.
- When the user leaves the customizaiton view, the current selection is applied to the robot.
