### ISSUE TITLE
2.4.3 As a user, I want to be able to acquire new skins when my score increases so that I feel rewarded.

### ISSUE THREAD

**Issue by em135** [Xitric/AR-Programming#37]
### Tasks
- [ ] 2.4.3.1 Add a view for unlocking various skins.
- [ ] 2.4.3.2 Add an entity to Core Data to keep track of the user’s available coins.
- [ ] 2.4.3.3 Reward the user with coins when completing a level.

### Acceptance criteria
- Display the user's current amount of coins.
- Display the costs of locked skins.
- Provide an option for buying a locked skin, which subtracts from the user's amount of coins.
- Reward the user only once for each star acquired in a level.
