### ISSUE TITLE
4.4.1 As a user, I want to be able to view levels of a specific difficulty so that I can play only the levels currently relevant for me.

### ISSUE THREAD

**Issue by Xitric** [Xitric/AR-Programming#41]
### Tasks
- [x] 4.4.1.1 Display names, types, and preview images of levels.
- [x] 4.4.1.2 Display a lock indicator over levels that are currently locked to the user.
- [x] 4.4.1.3 Create multiple pages in the level select view, each page containing levels of a certain difficulty.

### Acceptance criteria
- Levels are divided into 4 categories of difficulties.
- Users are able to start a level with no wrong navigations.
- Users are able to navigate to the difficulty category of levels that matches their own grade with no wrong navigations.
- Users are able to call out which levels are completed and which are locked when queried to do so, with no mistakes.
