### ISSUE TITLE
3.1.1 As a user I want to have a library of cards so that I can listen to descriptions of them without playing the game.

### ISSUE THREAD

**Issue by em135** [Xitric/AR-Programming#44]
### Tasks
- [x] 3.1.1.1 Display name, image, and descriptions of cards.
- [ ] 3.1.1.2 Read aloud the card description when it is pressed.
- [x] 3.1.1.3 Create sample sequences of cards that can be executed on a robot inside the card detail view.

### Acceptance criteria
- Cards are divided into 4 levels of complexities.
- Users are able to locate the information page on a card with no wrong navigations.
- Users are able to make the descriptions read aloud with no wrong presses.
- Users are able to navigate to the complexity class of cards that matches their own grade with no wrong navigations.
- Users are able to enter a free-play level to experiment with a card without navigating back to the main menu.
- Users are able to execute and discuss sample card sequences on their first or second try.
